name: Post Message on slack every hour
on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 * * * *"
jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run
        run: |
          pip3 install slack-sdk
          pip3 install requests
          pip3 install python-dotenv
          python3 ./bot.py
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      - name: Commit updates
        uses: EndBug/add-and-commit@v4
        with:
          author_name: bot
          author_email: bot@example.com
          message: "Update ts.txt"
          add: "*.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
